kind: ConfigMap
apiVersion: v1
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system
  labels:
    managed-by: azure
    managed-by-generator: manual
data:
  settings-configmap: |
    schema-version = "1"
    config-version = "ver.1"
    [pod-annotation-based-scraping]
    podannotationnamespaceregex = "app"
    [default-scrape-settings-enabled]
    kubelet = true
    cadvisor = true
    kubestate = true
    nodeexporter = true
