apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: "kv-learningsteps-1769"
    objects: |
      array:
        - |
          objectName: pg-admin-password
          objectType: secret
    tenantId: "c0531484-50fa-4ff2-97df-b1f2d4810603"