apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  # name: azure-kv-secrets
  name: azure-keyvault
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a29e9b49-e51b-414e-806f-515367a800ed"
    keyvaultName: "kv-learningsteps-1769"
    objects: |
      array:
        - |
          objectName: pg-admin-password
          objectType: secret
          objectVersion: ""                       # Optional: leave empty to use latest version
    tenantId: "c0531484-50fa-4ff2-97df-b1f2d4810603"