apiVersion: v1
kind: Service
metadata:
  name: api-service
  https://www.youtube.com/watch?v=bafijVfuzwYlabels:
    app: learningsteps # Added this for Prometheus to find
spec:
  type: LoadBalancer # Triggers Azure to create a public IP
  ports:
    - name: http       # Added this so the ServiceMonitor knows which port to scrape  
      port: 80
      targetPort: 8000
  selector:
    app: learningstepshttps://www.youtube.com/watch?v=bafijVfuzwY