apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system
data:
  schema-version: "v1"
  config-version: "ver1"
  default-scrape-settings-enabled: |-
    kubelet = true
    coredns = true
    cadvisor = true
    kubeproxy = true
    kubestate = true
    nodeexporter = true
  pod-annotation-based-scraping: |-
    podannotationnamespaceregex = "app"
